eclipse-glsp/glsp-server-node

.eslintrc.js, .mocharc.json, .vscode/launch.json, CHANGELOG.md, examples/workflow-server/package.json, package.json, packages/server-node/package.json, packages/server-node/src/actions/action-dispatcher.spec.ts, packages/server-node/src/actions/action-dispatcher.ts, packages/server-node/src/operations/create-operation-handler.ts, packages/server-node/src/test/mock-util.ts
- Implement `dispatchOnNextUpdate` for ActionDispatcher 
- Use  the new API in the `CreateOperationHandler` to automatically select newly created nodes.
Also:
- Consume new @eclipse-glsp/mocha-config package and remove redundant devdependencies
- Update debug config for workflow example
- Add missing CHANGELOG.md file
Closes eclipse-glsp/glsp/issues/507
=> #507 Implement `dispatchOnNextUpdate` for ActionDispatcher

.vscode/launch.json, packages/server-node/src/base-impl/delete-operation-handler.ts, packages/server-node/src/features/model/gmodel-index.ts
Update `GModelIndex` to set missing parent references during indexing. This ensures that deletion
of newly created elements works as expected.
Also update the implementaion of `DeleteOperationHandler` to use a `Logger` instance instead of console.log.
Fixes eclipse-glsp/glsp/issues/517
=> #507 Fix edge deletion for workflow example

.github/ISSUE_TEMPLATE/config.yml
Disable blank issues and add buttons that redirects to the GLSP umbrella repository and discussions board.
Part of https://github.com/eclipse-glsp/glsp/issues/529
=> #529 Add GitHub issue templates to the repositories

examples/workflow-server/src/workflow-diagram-module.ts, packages/server-node/src/actions/action-dispatcher.spec.ts, packages/server-node/src/base-impl/gmodel-diagram-module.ts, packages/server-node/src/di/binding-target.spec.ts, packages/server-node/src/di/binding-target.ts, packages/server-node/src/di/diagram-module.ts, packages/server-node/src/di/glsp-module.ts, packages/server-node/src/di/multi-binding.ts, packages/server-node/src/di/multi-bindings.spec.ts, packages/server-node/src/di/server-module.ts, packages/server-node/src/features/directediting/apply-label-edit-operation-handler.spec.ts, packages/server-node/src/launch/cli-parser.spec.ts, packages/server-node/src/launch/socket-cli-parser.spec.ts, packages/server-node/src/protocol/glsp-server.spec.ts, packages/server-node/src/test/integration-test.spec.ts, yarn.lock
Introduce the concept of `BindingTargets` which enables us to define bindings in the diagram and server modules in a more explicit way using dedicated submethods. (Similar to the pattern we currently use in the Java  GLSP Server).  Using `BindingTargets` allows us to move the specification of the target binding into a
submethod without limiting the power of inversify. Adopters can still chose whether they want to bind a service identifier to constructor, self, constant value or another service.
In addition, this change fixes a couple of issues in the test setup regarding error handling.
Fixes eclipse-glsp/glsp/issues/629
=> #620 Introduce explicit binding methods for diagram module

packages/graph/src/default-types.ts, packages/graph/src/gpre-shape-prerendered-element.ts, packages/graph/src/index.ts, yarn.lock
Add missing `GShapedPrerenderedElement` model element to the graph model.
This can be used to construct special shaped prerendered elements like `ForeignObjectElements`.
Also: Cleanup default type mappings
Requires: https://github.com/eclipse-glsp/glsp-client/pull/178
=> Add `GShapedPrerenderedElement` to graph model

examples/workflow-server/src/handler/create-activity-node-handler.ts, examples/workflow-server/src/handler/create-automated-task-handler.ts, examples/workflow-server/src/handler/create-category-handler.ts, examples/workflow-server/src/handler/create-decision-node-handler.ts, examples/workflow-server/src/handler/create-fork-or-join-node-handler.ts, examples/workflow-server/src/handler/create-manual-task-handler.ts, examples/workflow-server/src/handler/create-merge-node-handler.ts, examples/workflow-server/src/handler/create-task-handler.ts, packages/server-node/src/di/binding-target.spec.ts, packages/server-node/src/di/binding-target.ts
Update behavior of `applyBindingsTarget` for binding `ServiceTargets`.
Add an optional `autoBind` flag to `ServiceTarget` which is enabled by default.
If the target service identifier is not bound yet and this flag is enabled we check
whether the target service can be bound to itself in singleton scope.
If so we do that, otherwise we throw an error.
This covers the most common case for our `ServiceBindings`: Subclassing a default implementation and then bind the service identifier to this implementation.
(e.g. bind(MyModelState).toSelf().inSingletonScope();
bind(ModelState).toService(MyModelState))
For more complex binding configurations its still possible to access the binding context directly (this.context) and apply the bindings this way.
Closes …
=> GH-631 Improve to service bindings in diagram module

CHANGELOG.md, packages/server-node/src/features/model/model-state.ts, packages/server-node/src/gmodel-lib/gmodel-storage.ts
Introduce `updateRoot` method and make root setter protected
- Update changelog
Fixes https://github.com/eclipse-glsp/glsp/issues/639
=> GH-639 Align ModelState API with Java GLSP Server API

packages/server-node/src/di/diagram-module.ts, yarn.lock
This is to be consistent with the term source model that we now use to refer to the underlying model from which the GModel is created.
Build depends on https://github.com/eclipse-glsp/glsp-client/pull/184
https://github.com/eclipse-glsp/glsp/issues/655
=> Rename `ModelSourceChangedAction` to `SourceModelChangedAction`

packages/layout-elk/src/glsp-elk-layout-engine.ts
Edges that are children of ports should also be layouted by the GlspElkLayoutEngine.
Resolves eclipse-glsp/glsp#661
=> Layout edges that are children of ports

packages/server-node/src/features/model/gmodel-index.ts
I think we should include the current element in the search for an element or parent that matches the guard. This would then be inline with how it is in Sprotty and also better matches the current typedoc (the element to start the search from).
=> Start with current element

.github/workflows/codeql-analysis.yml, .gitignore, .vscode/launch.json, Jenkinsfile, README.md, examples/workflow-server/package.json, package.json, packages/graph/package.json, packages/layout-elk/package.json, packages/server-node/package.json, packages/server-node/src/features/model/gmodel-serializer.spec.ts, packages/server-node/src/launch/cli-parser.ts, yarn.lock
Update lerna and minimum node version
- https://github.com/eclipse-glsp/glsp/issues/676: 
Update to lerna 6 and set node 14 as minimum engine version
- https://github.com/eclipse-glsp/glsp/issues/812:
Improve yarn scripts
- Remove linting from prepare step
- Add dedicated :ci scrips for testing and linting
- Add 'all' script on root level
- Consistently sort scripts ascending
- https://github.com/eclipse-glsp/glsp/issues/680: 
Update to latest `@eclipse-glsp/config` version
- https://github.com/eclipse-glsp/glsp/issues/794: Update Jenkinsfile to
- directly include deploy step instead of spawning a new dedicated job
- enable error reporting when master builds fail
=> Update lerna and minimum node version

packages/server-node/src/launch/glsp-server-launcher.ts, packages/server-node/src/launch/socket-server-launcher.ts
The complete message on startup now returns the port accepting requests.
If the port is set to 0, OS automatically determines an open port. The port returned by the complete message is the effective port (the specified one if port was set and different of 0, and the effective port if port was set to 0).
Signed-off-by: Remi Schnekenburger [rschnekenburger@eclipsesource.com](mailto:rschnekenburger@eclipsesource.com)
=> Return port with startup complete message

.vscode/launch.json, packages/server-node/src/launch/socket-server-launcher.spec.ts, packages/server-node/src/launch/socket-server-launcher.ts
The socket server currently does not actually shutdown the server when calling shutdown.
In order to do so, the `close` method must be called on the server. Thus the server was moved into a private member
to be able to call `close` on `stop`.
This also fixes the test launch config and adds a test. Furthermore the overriden methods in SocketServerLauncher are not public anymore in order to have a clean api.
Contributed on behalf of STMicroelectronics.
=> Fix `stop` of socket server

packages/server/src/common/command/command-stack.spec.ts, packages/server/src/common/command/command-stack.ts, packages/server/src/common/command/command.spec.ts, packages/server/src/common/command/command.ts, packages/server/src/common/command/recording-command.spec.ts, packages/server/src/common/command/recording-command.ts, packages/server/src/common/command/undo-redo-action-handler.ts, packages/server/src/common/operations/operation-action-handler.ts, packages/server/src/common/test/mock-util.ts
Change command API to support `MaybePromise<void>` instead of just plain voids. This enables async command execution e.g. for communicating with a modelserver 
=> Support async command execution

.vscode/launch.json, README.md, examples/workflow-server/package.json, examples/workflow-server/src/browser/app.ts, examples/workflow-server/src/node/app.ts, examples/workflow-server/src/node/workflow-cli-parser.ts, package.json, packages/server/package.json, packages/server/src/browser/launch/worker-server-launcher.ts, packages/server/src/common/launch/glsp-server-launcher.ts, packages/server/src/node/launch/socket-server-launcher.ts, packages/server/src/node/launch/websocket-server-launcher.ts, yarn.lock
Requires https://github.com/eclipse-glsp/glsp-client/pull/215
Fixes https://github.com/eclipse-glsp/glsp/issues/945
=> Add websocket server launcher

.vscode/launch.json, CHANGELOG.md, examples/workflow-server/package.json, packages/server/src/node/launch/socket-cli-parser.ts
This sets the default port to 0, which will cause the server to automatically assign a port. The port is then printed to the console in the startup message and can be parsed by clients.
Part of eclipse-glsp/glsp#965
=> feat: adjust server startup to use autoassigned ports

.gitignore, examples/workflow-server-bundled/LICENSE, examples/workflow-server-bundled/README.md, examples/workflow-server-bundled/package.json, examples/workflow-server/README.md, examples/workflow-server/webpack.config.js
Introduce a `@eclipse-glsp-examples/workflow-server-bundle` package. This package just contains the bundled workflowserver without any direct dependencies to server components. It can be consumed in the dev example of the client repository without introducing a dependecy loop between client & server. 
This fixes eclipse-glsp/glsp/issues/1026. We can decide on a later point if want to move the protocol package into the umbrella repository. In regards to developer experience its probably better to keep it in the client repo. Changes to the protocol package typically also  require changes in the client and server repos. By keeping the package in one of the repositories in question we can reduce the required overhead with regards to merging and consuming the changes.
=> GLSP-1026 Provide bundle on example server package

CHANGELOG.md, packages/server/src/common/di/diagram-module.ts, packages/server/src/common/features/model/request-model-action-handler.ts, packages/server/src/common/features/progress/progress-service.ts, yarn.lock
Works with
* https://github.com/eclipse-glsp/glsp-client/pull/265
* https://github.com/eclipse-glsp/glsp-theia-integration/pull/168
https://github.com/eclipse-glsp/glsp/issues/1019
=> Add support for server progress reporting

packages/server/src/common/features/model/request-model-action-handler.ts, packages/server/src/common/utils/client-options-util.ts
If Websocket connections reconnect after an interrupt, ensure that the last modelState is restored on RequestModelAction if available
Part of https://github.com/eclipse-glsp/glsp/issues/77
---
Related to: https://github.com/eclipse-glsp/glsp-client/pull/269
=> GLSP-77: Allow WebSocket connections to reconnect after interrupt

examples/workflow-server-bundled/package.json, packages/server/src/node/abstract-json-model-storage.ts
Ensure leading shashes in File urls are properly handled under Windows. 
Also: Fix rimraf command that was not working under Windows 
Fixes https://github.com/eclipse-glsp/glsp/issues/1101
=> GLSP-1101: Fix Windows path  conversion

packages/server/package.json, packages/server/src/node/abstract-json-model-storage.ts, packages/server/src/node/launch/cli-parser.ts, yarn.lock
Use 'fs' instead of 'fs-extra' in GLSP server node as the additional capatibilities of 'fs-extra' are not used. Also fixes the issue that the dependency to 'fs-extra' was not declared in the 'package.json' which might fail consumer builds.
Contributed on behalf of STMicroelectronics.
=> GLSP-1109: Remove dependency to fs-extra

.vscode/launch.json, packages/server/src/common/actions/action-dispatcher.spec.ts, packages/server/src/common/actions/action-dispatcher.ts, packages/server/src/common/actions/client-action-handler.ts, packages/server/src/common/actions/global-action-provider.spec.ts, packages/server/src/common/actions/global-action-provider.ts, packages/server/src/common/di/client-session-module.ts, packages/server/src/common/di/diagram-module.ts, packages/server/src/common/di/server-module.ts, packages/server/src/common/features/model/model-submission-handler.ts, packages/server/src/common/features/model/request-model-action-handler.ts, packages/server/src/common/operations/operation-action-handler.ts, packages/server/src/common/protocol/client-action.ts, packages/server/src/common/protocol/glsp-server.spec.ts, packages/server/src/common/protocol/glsp-server.ts, packages/server/src/common/session/client-session-factory.spec.ts, packages/server/src/common/session/client-session-factory.ts, packages/server/src/common/session/client-session-manager.spec.ts, tsconfig.eslint.json, yarn.lock
- Refactor `ModelSubmissionHandler` to support proper handling of the `RequestModelAction` as real request action 
Part-of: https://github.com/eclipse-glsp/glsp/issues/1116
Refactor the base GLSP protocol to allow the client to tell the server which actions it is going to handle i.e. which actions should be forwarded to the client
- Add `clientActions` array to `InitializeClientSessionParams`. This means the client now has to pass the action kinds it wants to handle as part of the initalize request
- Replace `ClientActionHandler` with `ClientActionForwader` a separate component that is not part of the server-side action handlers. 
- Remove `configureClientActions` method from `DiagramModule` as the explicit configuration is no longer needed
Part of eclipse-glsp/glsp/issues/1117
=> Adapt to latest protocol changes

examples/workflow-server/src/node/app.ts, packages/server/src/common/actions/action-dispatcher.spec.ts, packages/server/src/common/command/recording-command.ts, packages/server/src/common/features/model/model-submission-handler.ts, packages/server/src/common/features/model/request-model-action-handler.ts, packages/server/src/common/utils/promise-queue.ts, yarn.lock
-  Ensure that `RequestModelActionHandler` invokes correct ModelSubmissionHandler method (`submitInitialModel)
- Ensure that `ModelSubmissionHandler` dispatches correct `SetModelAction` Misc:
- Fix some aync calls that were not properly awaited
- Remove require import from `action-disptacher.spec.ts`
Part of: eclipse-glsp/glsp/issues/1116
Works with: https://github.com/eclipse-glsp/glsp-client/pull/288
=> GLSP-1116: Fix RequestModelActionHandler

examples/workflow-server/webpack.config.js, packages/server/src/common/command/recording-command.spec.ts, packages/server/src/common/command/recording-command.ts, packages/server/src/common/features/model/model-state.ts, packages/server/src/common/features/model/model-submission-handler.ts, packages/server/src/common/gmodel/gmodel-create-edge-operation-handler.ts, packages/server/src/common/gmodel/gmodel-create-node-operation-handler.ts, packages/server/src/common/index.ts, packages/server/src/common/operations/compound-operation-handler.ts, packages/server/src/common/operations/create-operation-handler.ts, packages/server/src/common/operations/json-operation-handler.ts, packages/server/src/common/operations/operation-handler-registry.ts, packages/server/src/common/operations/operation-handler.ts, packages/server/src/common/utils/registry.spec.ts, packages/server/src/common/utils/registry.ts
- Provides  generic,reusable operation handler implementations for JSON-based source models
- Refactor `RecordingCommand` API
- Refactor `CreationOperationHandler` interfaces to be more strict (Previously it was possible to  declare a handler with mixed (nodes/edges) types) 
- Also: Filter out non-critical warning in webpack config
Fixes https://github.com/eclipse-glsp/glsp/issues/891
For testing use: https://github.com/eclipse-glsp/glsp-examples/pull/193
=> GLSP-891: Json operation handler API

packages/server/src/common/gmodel/cut-operation-handler.ts, packages/server/src/common/gmodel/delete-operation-handler.ts
- Fix cut operation handler Ensure that the GModelCutOperation handler does not execute a command itself and instead dispatches a corresponding DeleteOperation
- Fix dependecy resolvement in delete-operaetion handler
=> Bugfixes for 2.0

packages/server/src/common/command/recording-command.ts, packages/server/src/common/operations/json-operation-handler.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1162
=> Ensure 'postChange' is properly handled as async

.vscode/settings.json, packages/server/src/common/features/model/gmodel-index.ts, packages/server/src/common/gmodel/delete-operation-handler.ts
- Ensure that the element to delete is removed from its direct parent instead of always using the model root
- Remove lookup of topLevel node or edge before deletion.
- Ensure that edges of ports are also considered during dependants collection
- Avoid adding of child elements to the dependants collection (as they are implicitly deleted when deleting the parent)
- Fix to narrow typing in GModelIndex.getIncomingEdges
Fixes https://github.com/eclipse-glsp/glsp/issues/1163
=> GLSP-1163: Fix GModelCreateNodeOperationHandler

examples/workflow-server/src/common/handler/create-activity-node-handler.ts, examples/workflow-server/src/common/handler/create-category-handler.ts, examples/workflow-server/src/common/handler/create-task-handler.ts, packages/server/src/common/gmodel/gmodel-create-node-operation-handler.ts, packages/server/src/common/operations/json-operation-handler.ts, yarn.lock
Requires https://github.com/eclipse-glsp/glsp-client/pull/301
Relates to https://github.com/eclipse-glsp/glsp/issues/1159
=> Add ghost elements to tool palette items through trigger actions

packages/server/src/common/operations/json-operation-handler.ts
Make runnable of command return a MaybePromise to be consistent with the doExecute method of recording commands and support async recordings.
=> Ensure async usage of JsonOperationHandler.commandOf

packages/server/src/common/features/model/model-submission-handler.ts
In the `submmitModelDirectly` method of the `ModelSubmissionHandler` the gmodel serialization was invoked before the layout engine was executed (in automatic layouting mode). As a consequence the model sent to the server reflected the unlayouted state.
Fixes https://github.com/eclipse-glsp/glsp/issues/1227
=> GLSP-1227: Ensure that model update is correct when using autolayout

packages/graph/src/galignable.spec.ts, packages/graph/src/galignable.ts, packages/graph/src/gbounds-aware.spec.ts, packages/graph/src/gbounds-aware.ts
- Fix handling of zero values in `GBoundsAwareBuilder` functions
- Fix handling of zero values in `GAlignableBuilder` function
- Adds unit tests for those updated functions
Resolves eclipse-glsp/glsp/issues/1266
=> GLSP-1266 Fix handling of zero values in builder functions

.gitignore, examples/workflow-server-bundled/package.json, packages/layout-elk/src/di.config.ts
As described in the comment, but `elkjs` wants to instantiate workers. If no `workerFactory` is given, it tries to resolve this using a fake worker from `elk-worker.min.js`, which is seemingly available when started through node, but not in a web-worker context. Since it is a dynamic import unknown to webpack, it is not bundled.
Therefore, I simply assigned a simple stub, since the worker functionality of `elkjs` is not needed. This enables the server to start in a worker as expected.
=> Fixed webworker startup bc elkjs hidden dependency

examples/workflow-server/src/node/app.ts, packages/server/src/node/di/winston-logger.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1195
- Ensure that the WinstonLogger does not throw an error if it encounters an unparseable object (e.g. circular structure)
- Add fallback hooks for uncaught exceptions/promise rejections to example server to avoid nodes default behavior (process exit)
=> GLSP-1195: Handle parsing errors in winston logger

.gitignore, examples/workflow-server-bundled/package.json, examples/workflow-server/src/browser/app.ts, packages/layout-elk/src/di.config.ts
As requested in #78, the change is now restricted to browser/web-worker context.
=> Mocked workerFactory only for webworker context

examples/workflow-server/src/common/workflow-diagram-configuration.ts, examples/workflow-server/src/common/workflow-edge-creation-checker.ts
Refactor createDefault hint functions to allow partial overriding of default properties
Update type hints configuration for workflow example to make fork and join nodes not resizable => we have test cases for both resizable and non-resizable elements in the diagram
=> Configure fork and join nodes as not resizable

CHANGELOG.md, examples/workflow-server/src/common/workflow-popup-factory.ts, packages/graph/src/gedge-layoutable.ts, packages/graph/src/gissue-marker.ts, packages/server/package.json, packages/server/src/common/actions/action-dispatcher.ts, packages/server/src/common/features/model/request-model-action-handler.ts, packages/server/src/common/utils/client-options-util.ts, yarn.lock
- Change visibility of private fields to protected for better extensibility
- Update to latest protocol version
- This introduces a minor unavoidable API break because GIssue has changed from a class to an interface definition
- Ensure that actions queued with `dispatchAfterNextUpdate` are also dispatched after the initial `SetModelAction`
- Fix copyright header violations
=> Minor cleanup

examples/workflow-server/src/common/provider/node-documentation-navigation-target-provider.ts
Update the NodeDocumentationNavigationTargetProvider to not rely on the tasks name which is currently unreliable (see https://github.com/eclipse-glsp/glsp/issues/1351) and instead relies on the `text` property of the tasks label.
Fix workflow documentation navigation example
- Build and start
- Connect the Theia or vscode integration example (by starting in debug mode)
- Verify that Go to documentation on the "push" node works)
=> Fix workflow documentation navigation example

examples/workflow-server/src/common/workflow-diagram-configuration.ts
Part of https://github.com/eclipse-glsp/glsp/issues/1369
- Ensure that the type hint for weighted edges if created with the correct `elementTypeId`
=> GLSP-1369 Fix wrong edge type hint

packages/server/src/common/reexport.ts, yarn.lock
Contributed on behalf of Axon Ivy AG
Part of https://github.com/eclipse-glsp/glsp/issues/1381
Requires https://github.com/eclipse-glsp/glsp-client/pull/384
- Everything should still work as expected.
=> Ensure JsonrpcClientProxy is injectable in the Node Server context

packages/server/src/common/reexport.ts, yarn.lock
Remove unnecessary re-decoration, part of protocol DI import/export
Part of https://github.com/eclipse-glsp/glsp/issues/1381
=> Remove unnecessary re-decoration, part of protocol DI import/export

packages/graph/src/default-types.ts
Ensure that the correct type for `foreign-object` is configure and add missing configuration for GShaprePreRenderedElements
Fixes https://github.com/eclipse-glsp/glsp/issues/1398
=> Fix default type mappings

packages/server/package.json, packages/server/src/common/features/model/model-submission-handler.ts, yarn.lock
See also https://github.com/eclipse-glsp/glsp-server/pull/247
Fixes https://github.com/eclipse-glsp/glsp/issues/1408
- Add breakpoint during validation and see that the diagram still shows up with the 'Validating model...' message being present.
=> Align Node server validation with Java server (async live validation)

packages/server/src/common/gmodel/change-bounds-operation-handler.ts, packages/server/src/common/gmodel/change-routing-points-operation-handler.ts, packages/server/src/common/operations/compound-operation-handler.ts, packages/server/src/common/operations/operation-action-handler.ts
- Filter empty change bounds and change routing points operations
- Filter empty compound commands
- Ensure we only submit a new model if actual changes were applied
Relates to  https://github.com/eclipse-glsp/glsp/issues/1477
- Move an element without actually snapping to a new position
- Debug server state or observer undo/redo stack is correctly as there are no operations on the command stack
-   [x] This PR should be mentioned in the changelog **IF the submission change is accepted as well**
-   [x] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
- If the submission change is accepted as well, this may change the behavior in a way that the GModel is not re-generated after an empty operation. Adopters may have relied …
=> Avoid executing unnecessary operations

packages/server/src/common/utils/console-logger.ts
- Ensure ConsoleLogger logs the correct log level of the message
- See that logged messages using different log levels (info, warn, ...) actually show the correct log level next to the logged message.
=> Ensure ConsoleLogger logs the correct log level of the message

packages/server/src/node/di/app-module.ts
Avoid unnecessary instanciation of the winston logger if logging is disabled via options (noConsoleLog and noFilelog are true)
Start the server with noConsoleLog enabled. On master this prints a warning since we still instantiate the winston logger although both console and file log are disabled:
```ts
❯ yarn start --no-consoleLog
yarn run v1.22.22
$ yarn --cwd examples/workflow-server-bundled start --no-consoleLog
$ node --enable-source-maps ./wf-glsp-server-node.js --port 5007 --no-consoleLog
[winston] Attempt to write logs with no transports, which can increase memory usage: {"message":"[SocketServerLauncher] The GLSP server is ready to accept new client requests on port: 5007 ","level":"info"}
[GLSP-Server]:Startup completed. Accepting requests on port:5007
```
With the PR this should …
=> Improve winston configuration

packages/layout-elk/package.json, packages/layout-elk/src/di.config.ts, packages/layout-elk/src/glsp-elk-layout-engine.ts, packages/server/src/common/features/model/model-state.ts, yarn.lock
- Update to elkjs 0.10.1
- Ensure that Logger can used in elkLayoutModule
- Update GLSPElkLayoutEngine
- Fix typing issue of GModelState.editMode
Fixes eclipse-glsp/glsp/issues/1313
Can be tested with the standalone example. Invoking the layout command (Ctrl+Shift+L) should work as before.
-   [x] This PR should be mentioned in the changelog
-   [x] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)
- [layout] Updated `GLSPElkLayoutEngine` for `elkjs` > 0.10.1.
- `GLSPElkLayoutEngine`: Replaced usages of the `deprecated` and no longer supported `ELKPrimitiveEdge`. This might affect adopters that use a customization of this class
=> GLSP-1313: Update elkjs
